# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: generate-markdown

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run python script
      run: python utils/generate_toc.py
    - uses: EndBug/add-and-commit@v7.0.0
      with:
        author_name: github-actions
        message: '🔨 README TOC update - Github action'
        author_email: 41898282+github-actions[bot]@users.noreply.github.com